# Generated by Django 3.0.8 on 2020-10-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musterdaten', '0002_auto_20200827_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['title'], 'verbose_name': 'Datensatz', 'verbose_name_plural': 'Datensätze'},
        ),
        migrations.AlterModelOptions(
            name='modeldataset',
            options={'ordering': ['title'], 'verbose_name': 'Musterdatensatz', 'verbose_name_plural': 'Musterdatensätze'},
        ),
        migrations.AlterModelOptions(
            name='modelsubject',
            options={'ordering': ['title'], 'verbose_name': 'Thema', 'verbose_name_plural': 'Themen'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['id'], 'verbose_name': 'Bewertung', 'verbose_name_plural': 'Bewertungen'},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='modeldataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='musterdaten.Modeldataset'),
        ),
        migrations.CreateModel(
            name='Top3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='top3_modeldatasets', to='musterdaten.Dataset')),
                ('modeldataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musterdaten.Modeldataset')),
            ],
        ),
    ]
