# Generated by Django 3.0.8 on 2020-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musterdaten', '0003_auto_20200828_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=128, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(verbose_name='beschreibung'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='original_id',
            field=models.CharField(max_length=512, verbose_name='portal_id'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(max_length=512, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='license',
            name='short_title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='license',
            name='title',
            field=models.CharField(max_length=128, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='modeldataset',
            name='title',
            field=models.CharField(max_length=128, verbose_name='titel'),
        ),
    ]
