# Generated by Django 3.0.8 on 2020-12-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musterdaten', '0005_dataset_top_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoMatchScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=32)),
                ('topic', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musterdaten.Dataset')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
