# Generated by Django 3.0.8 on 2021-01-13 09:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('musterdaten', '0007_auto_20210111_0908'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='score',
            managers=[
                ('total_datasets', django.db.models.manager.Manager()),
            ],
        ),
    ]
