# Generated by Django 3.0.8 on 2021-01-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musterdaten', '0008_auto_20210113_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomatchscore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='musterdaten.CustomUser'),
        ),
    ]
